## `Importing and displaying datasets`

### <u>All imports goes here!</u>

In [ ]:
import pandas as pd
from IPython.display import display

In [3]:
result_2008 = pd.read_csv('Data/Cleaned_Data/cleaned_&_final_2008_result.csv')
result_2013 = pd.read_csv('Data/Cleaned_Data/cleaned_&_final_2013_result.csv')
result_2017 = pd.read_csv('Data/Cleaned_Data/cleaned_&_final_2017_result.csv')
result_2022 = pd.read_csv('Data/Cleaned_Data/cleaned_&_final_2022_result.csv')

display(result_2008.head())
display(result_2013.head())
display(result_2017.head())
display(result_2022.head())

,Unnamed: 0,District,Const,WParty,WVotes,Age,TurnOut%
0,0,Achham,Achham 1,uml,2119.0358,40,54.53
1,1,Achham,Achham 2,maoist,1708.7270,32,52.82
2,2,Arghakhanchi,Arghakhanchi 1,maoist,1966.7836,46,55.34
3,3,Arghakhanchi,Arghakhanchi 2,nepalicongress,1755.1260,46,52.05
4,4,Baglung,Baglung 1,maoist,1828.5047,48,60.01

,Unnamed: 0,District,Const,WParty,WVotes,Age,TurnOut%
0,0,Taplejung,Taplejung-1,Nepal Communist Party (UML),7434.0,37.0,73.12
1,1,Taplejung,Taplejung-2,Nepal Communist Party (UML),7034.0,48.0,72.60
2,2,Panchthar,Panchthar-1,Nepal Communist Party (UML),13082.0,26.0,72.18
3,3,Panchthar,Panchthar-2,Nepali Congress,11839.0,41.0,74.58
4,4,Illam,Illam-1,Nepal Communist Party (UML),17342.0,55.0,78.58

,Unnamed: 0,District,Const,WParty,WVotes,Age,TurnOut%
0,0,Taplejung,Taplejung-1,Nepal Communist Party (UML),15417,46,59.060916
1,1,Taplejung,Taplejung-1,Nepali Congress,10974,51,62.215124
2,2,Taplejung,Taplejung-1,Federal Democratic National Front,861,57,54.605809
3,3,Taplejung,Taplejung-1,Naya Shakti Party Nepal,267,41,52.116411
4,4,Taplejung,Taplejung-1,Federal Socialist Forum Nepal,158,45,67.288690

,Unnamed: 0,District,Const,WParty,WVotes,Age,TurnOut%
0,0,Taplejung,Taplejung-1,Nepal Communist Party (UML),21943,56,49.859126
1,1,Taplejung,Taplejung-1,Nepal Communist Party (Maoist Center) (Unified...,21735,46,53.744678
2,2,Taplejung,Taplejung-1,Federal Democratic National Front,941,56,54.895159
3,3,Taplejung,Taplejung-1,"Janata Samajwadi Party, Nepal",628,49,51.052482
4,4,Taplejung,Taplejung-1,Rastriya Prajatantra Party,406,65,54.328004